### ISSUE TITLE
DSDT question

### ISSUE THREAD

**Issue by Bobbm** [korzhyk/Clover_GA-H97-D3H#1]
i have almost same mobo, but i5-4460 and no external GFX   

i am considering using/adapting your clover EFI setup.

i am H97M-D3H, a few minor differences, 
              H97M                       H97
PCIe        no (only 3.0)           yes
eSATA      no                           yes
M.2          no                            yes
Aud        ALC892                 ALC1150
LAN       Realtek                     intel

currently my config.plist uses "new way" DSDT patches, but I see that you do not. 

Do you use a separate DSDT instead? 

I am confused. thanks

**Comment by korzhyk** [comment]
Hi, I did't use a separate DSDT. Everything works great without modified DSDT. I use only https://github.com/korzhyk/Clover_GA-H97-D3H/blob/master/H97-D3H-CF/config.plist#L14 for correcting CPU GPU name. And CPU GPU https://github.com/korzhyk/Clover_GA-H97-D3H/blob/master/H97-D3H-CF/config.plist#L140 ingection **ig-platform-id**.

And you must use a working kexts for LAN and Audio (https://github.com/toleda/audio_RealtekALC or https://github.com/vit9696/AppleALC **new**)
